name: Release
on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  gh-pages:
    needs: build
    uses: ./.github/workflows/gh-pages.yml
    permissions:
      contents: write
